import mysql.connector
connection = mysql.connector.connect(host="localhost",username="root",password="Mukesh@2003",database="db")
print("Database opened successfully")
cursor = connection.cursor()
#delete
# # cursor.execute('''DROP TABLE Assignments;''')
# # cursor.execute('''DROP TABLE Records;''')
# # cursor.execute('''DROP TABLE Student_Info;''')
# cursor.execute('''DROP TABLE detail;''')
cursor.execute("create table faculty (id INT AUTO_INCREMENT UNIQUE KEY,facno varchar(10) PRIMARY KEY,password VARCHAR(255))")
print("Table created successfully")
cursor.execute("create table detail (name varchar(255),rollno varchar(10) PRIMARY KEY,password VARCHAR(255))")
print("Table created successfully")
cursor.execute("create table Student_Info (id INT AUTO_INCREMENT UNIQUE KEY, name VARCHAR(255) NOT NULL, roll_number VARCHAR(10) PRIMARY KEY, total_classes INT,classes_attended INT,attendance_percent INT)")
print("Table created successfully")
cursor.execute("create table Assignments (id INT AUTO_INCREMENT PRIMARY KEY, roll_num VARCHAR(10),Assignment_name VARCHAR(255) NOT NULL,file_name VARCHAR(255) NOT NULL ,filedata LONGBLOB,FOREIGN KEY(roll_num) REFERENCES Student_Info(roll_number))")
print("Table created successfully")
cursor.execute("create table Records (id INT AUTO_INCREMENT PRIMARY KEY, roll_num VARCHAR(10),record_name VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL,filedata LONGBLOB,FOREIGN KEY(roll_num) REFERENCES Student_Info(roll_number))")
print("Table created successfully")
connection.close()   